// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'E:/cwj/cwj-components-doc/node_modules/dumi/theme-default/slots/ContentFooter/index.js';
